import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { resolve, dirname } from 'node:path';
import { RubricCatalogSchema } from '@repofy/contracts';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '../../..');
const directory = resolve(root, 'repofy-backend/src/domain/rubrics/manifests');
const read = async name => JSON.parse(await readFile(resolve(directory, `${name}.v1.json`), 'utf8'));
const catalog = RubricCatalogSchema.parse({
  contractVersion: '1.0.0', manifestVersion: '1.0.0', releaseId: 'readiness_1_0_0',
  taxonomy: await read('taxonomy'),
  rubrics: await Promise.all(['backend', 'frontend', 'full_stack', 'mobile', 'ai_application'].map(read)),
});
const payload = JSON.stringify(catalog, null, 2);
if (payload.includes('$rubric_manifest$')) throw new Error('Reserved seed delimiter in manifest');
const sql = `-- Generated by npm run rubrics:seed:generate. Never edit a published seed; add a new version.\n` +
  `SELECT feature_one_private.import_rubric_release($rubric_manifest$\n${payload}\n$rubric_manifest$::jsonb);\n` +
  `-- Bootstrap only: repeated import must not move an operator's active pointer.\n` +
  `INSERT INTO public.feature_one_active_rubrics(singleton, release_id) VALUES (true, 'readiness_1_0_0') ON CONFLICT DO NOTHING;\n`;
const destination = resolve(root, 'supabase/migrations/20260913000500_initial_rubrics.sql');
const args = process.argv.slice(2);
if (args.some(arg => arg !== '--write') || args.length > 1) throw new Error('Usage: validate.mjs [--write]');
if (args.includes('--write')) await writeFile(destination, sql);
else if (await readFile(destination, 'utf8') !== sql) throw new Error('Seed differs from validated manifests. Published versions need a new migration.');
console.log(`Valid rubric release ${catalog.releaseId}: ${catalog.taxonomy.capabilities.length} capabilities, five roles; uncalibrated, detectors pending.`);
