"use client";

import { AnimateOnView } from "@/components/ui/animate-on-view";
import { SectionHeader } from "@/components/ui/section-header";
import { Badge } from "@/components/ui/badge";
import {
  FileSearch,
  Radar,
  GraduationCap,
  AlertTriangle,
  MessageSquareText,
  Star,
} from "lucide-react";

const plannedFeatures = [
  {
    icon: Radar,
    label: "6-axis Developer DNA",
    description:
      "Code Quality, Complexity, Breadth, Practices, Consistency, and Collaboration scored on a radar chart",
  },
  {
    icon: Star,
    label: "Per-repo code grades",
    description:
      "Every repository graded on Code Quality, Testing, and CI/CD with A-through-C tier scoring",
  },
  {
    icon: AlertTriangle,
    label: "Strengths & red flags",
    description:
      "Automatically surface what stands out — both the good and the concerning patterns",
  },
  {
    icon: MessageSquareText,
    label: "Interview questions",
    description:
      "AI-generated questions tailored to the candidate's actual code and projects",
  },
  {
    icon: GraduationCap,
    label: "Hire recommendation",
    description:
      "Overall score with a hiring recommendation and estimated seniority level",
  },
  {
    icon: FileSearch,
    label: "Exportable PDF",
    description:
      "Share the full analysis as a polished multi-page PDF with your hiring team",
  },
];

export function AnalysisPreview() {
  return (
    <section id="analysis" className="py-20">
      <AnimateOnView>
        <SectionHeader
          title="AI Developer Analysis"
          subtitle="A hiring-grade evaluation generated by AI. Every metric backed by real code."
        />
      </AnimateOnView>

      <AnimateOnView delay={0.1}>
        <div className="rounded-lg border border-cyan/20 bg-cyan/5 p-8 sm:p-10">
          <div className="flex flex-col items-center text-center">
            <div className="flex h-12 w-12 items-center justify-center rounded-full border border-cyan/30 bg-cyan/10">
              <FileSearch className="h-6 w-6 text-cyan" />
            </div>
            <Badge
              variant="outline"
              className="mt-4 font-mono text-xs text-cyan border-cyan/30"
            >
              Coming Soon
            </Badge>
            <h3 className="mt-4 font-mono text-lg font-bold">
              Hiring-Grade Developer Reports
            </h3>
            <p className="text-muted-foreground mt-2 max-w-lg text-sm">
              Paste a GitHub username and get a comprehensive AI-generated
              evaluation — complete with scores, grades, strengths, red flags,
              and tailored interview questions. Everything backed by real code.
            </p>
          </div>

          <div className="mt-8 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
            {plannedFeatures.map((feature) => (
              <div
                key={feature.label}
                className="rounded-md border border-border bg-background/50 p-4"
              >
                <feature.icon className="h-4 w-4 text-cyan" />
                <p className="mt-2 font-mono text-xs font-bold">
                  {feature.label}
                </p>
                <p className="text-muted-foreground mt-1 text-[11px] leading-relaxed">
                  {feature.description}
                </p>
              </div>
            ))}
          </div>
        </div>
      </AnimateOnView>
    </section>
  );
}
