import type { ROLE_IMPLEMENTATION_KINDS } from "@repofy/contracts";
import type { Definition } from "./registry";

// New observations describe concrete controls. Existing observations and their
// strength ceilings remain unchanged, including the narrow native-button signal.
export const roleDefinitions: Record<typeof ROLE_IMPLEMENTATION_KINDS[number], Definition> = {
  labelled_control: { capabilities: ["frontend_accessibility", "frontend_interaction"], ecosystems: ["react"],
    required: "A returned form has a literal label/for and matching input/id, a controlled value and connected change handler, and a named submit button.",
    observation: "A form connects a labelled controlled input and a named submit action.",
    limitation: "Static label wiring does not establish computed accessibility, keyboard behavior, focus recovery or conformance." },
  native_accessible_action: { capabilities: ["frontend_accessibility", "frontend_interaction"], ecosystems: ["react-native"],
    required: "A returned React Native Pressable has literal button semantics, a nonempty accessibility label and a resolved local onPress action.",
    observation: "A React Native press action declares a button role and an accessibility label.",
    limitation: "Device accessibility behavior, touch targets, focus order and assistive-technology results are unverified." },
  state_transition: { capabilities: ["frontend_state"], ecosystems: ["javascript"],
    required: "A reducer switches on its action type, returns a copied state with a payload update for a literal case and returns the original state by default.",
    observation: "A reducer returns an immutable state update for a named action and preserves state for unknown actions.",
    limitation: "Only this reducer transition is observed; race handling, external state synchronization and every action are unverified." },
  validated_boundary: { capabilities: ["architecture_modularity", "architecture_boundaries", "security_input_handling"], ecosystems: ["zod"],
    required: "A function parses its input with a local object schema and directly returns a call into a different included module with that parsed binding.",
    observation: "A module validates its input before forwarding the parsed value across a resolved local module boundary.",
    limitation: "A single boundary does not establish system-wide layering, dependency direction or comprehensive validation." },
  mobile_subscription: { capabilities: ["mobile_lifecycle"], ecosystems: ["react-native"],
    required: "An AppState change subscription calls a local handler and its enclosing function returns an unconditional remove callback for the same subscription.",
    observation: "An AppState change listener is paired with a returned disposal callback.",
    limitation: "Registration and disposal wiring does not prove the caller invokes cleanup, permission recovery or native lifecycle execution." },
  mobile_navigation: { capabilities: ["mobile_navigation"], ecosystems: ["expo-router"],
    required: "A function parses its input and pushes a literal route pathname with params taken from the parsed value through the imported router.",
    observation: "An Expo route transition uses a literal pathname and validated parameters.",
    limitation: "Route existence, deep-link authorization, restoration and native back-stack behavior are unverified." },
  mobile_cache: { capabilities: ["mobile_offline", "reliability_recovery"], ecosystems: ["@react-native-async-storage/async-storage"],
    required: "A try awaits a local operation, caches its serialized result and returns it; catch reads and parses the same literal storage key.",
    observation: "A local result is cached and a caught failure falls back to the same stored record.",
    limitation: "Cache freshness, conflict resolution, storage failures and offline execution are unverified; this is not a complete synchronization protocol." },
  secret_configuration: { capabilities: ["security_secrets"], ecosystems: ["node"],
    required: "A function reads one environment binding, rejects a missing value with an inert error, and passes it directly to a local operation.",
    observation: "A function obtains a credential from environment configuration and rejects a missing value before use.",
    limitation: "This one configuration path does not establish secret rotation, secure deployment storage or absence of leaks elsewhere." },
  secure_storage: { capabilities: ["security_secrets"], ecosystems: ["expo-secure-store"],
    required: "An awaited SecureStore write uses a literal key and a function parameter as its value.",
    observation: "A function passes its input to an awaited platform secure-storage write.",
    limitation: "Platform configuration, persistence results, deletion and access-control behavior are unverified." },
  resource_guard: { capabilities: ["security_authorization"], ecosystems: ["javascript"],
    required: "A function rejects differing actor and resource owner identifiers before passing that resource to a resolved local operation.",
    observation: "An ownership comparison rejects a mismatching actor before a local resource operation.",
    limitation: "The caller's identity, resource provenance, race safety and protection of other entry points are unverified." },
  model_context: { capabilities: ["ai_context"], ecosystems: ["ai"],
    required: "A structured model call uses a prompt built by slicing a parameter array to a literal bound, mapping one property and joining the text.",
    observation: "A structured model prompt is constructed from a bounded number of context records.",
    limitation: "Record authorization, relevance, token length, retrieval quality and injection resistance are unverified." },
  model_action_guard: { capabilities: ["ai_safety"], ecosystems: ["ai"],
    required: "A structured model result is checked against an explicit literal action allowlist before a resolved local action consumes that same value.",
    observation: "A model-selected action is checked against a literal allowlist before local dispatch.",
    limitation: "This bounded dispatch guard does not establish prompt-injection resistance, tool authorization or safe model behavior overall." },
  evaluation_harness: { capabilities: ["ai_evaluation"], ecosystems: ["javascript"],
    required: "A bounded literal case list is evaluated through a local async implementation and explicit expected values are compared into returned results.",
    observation: "An evaluation loop records equality comparisons between local implementation results and explicit expected case outputs.",
    limitation: "Case representativeness, metric quality, passing results and model quality are unverified." },
  safe_diagnostic: { capabilities: ["observability_diagnostics"], ecosystems: ["pino"],
    required: "A caught failure logs only a literal structured code and operation through an imported pino logger.",
    observation: "A failure path emits a structured diagnostic containing literal fields.",
    limitation: "This event does not establish comprehensive logging, production delivery, correlation or absence of sensitive logs elsewhere." },
  health_probe: { capabilities: ["observability_health"], ecosystems: ["javascript"],
    required: "A local dependency is awaited in try, followed by an explicit healthy return; catch returns an explicit unavailable status.",
    observation: "A dependency probe distinguishes successful completion from a caught failure in its returned status.",
    limitation: "Probe scheduling, service exposure, timeout behavior and actual deployed health are unverified." },
  asserted_failure: { capabilities: ["testing_failures", "testing_behavior"], ecosystems: ["vitest", "@jest/globals"],
    required: "A non-skipped test asserts a throw or awaited rejection from a resolved local implementation with an explicit expected error.",
    observation: "A test source asserts an expected failure from a resolved local implementation.",
    limitation: "The assertion was not executed; fixture adequacy, passing results and coverage are unverified." },
  asserted_ui: { capabilities: ["testing_behavior"], ecosystems: ["@testing-library/react", "@testing-library/react-native"],
    required: "A non-skipped test renders one resolved local component and asserts a named-role query from that render using explicit testing-library imports.",
    observation: "A component test renders a local component and asserts an element located by its role and accessible name.",
    limitation: "Source assertions do not establish passing UI tests, user interaction, device behavior or accessibility conformance." },
  asserted_value: { capabilities: ["testing_behavior"], ecosystems: ["vitest", "@jest/globals"],
    required: "A non-skipped test asserts a property of an imported local immutable declaration, with the reference resolved to its initializer.",
    observation: "A test assertion inspects a property of a resolved local declaration.",
    limitation: "Source assertions do not prove deployed schema constraints, successful execution or data integrity." },
};
